// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://eclcwxnlkpaqvcyxrqgt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVjbGN3eG5sa3BhcXZjeXhycWd0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDE4OTQ4MzgsImV4cCI6MjA1NzQ3MDgzOH0.Qez0FD3_bk7MfQmp98zPVAAFLvDgnGUZ15D_qDusuXw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);